version: "3.9"

services:
  mariadb:
    image: mariadb:10.6
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - erpnext-network

  erpnext:
    image: frappe/erpnext:v15
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mariadb
    ports:
      - "${ERPNEXT_PORT}:8000"
      - "${SOCKETIO_PORT}:9000"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
    volumes:
      - erpnext-data:/home/frappe/frappe-bench/sites
      - ./repos.json:/home/frappe/frappe-bench/repos.json
    networks:
      - erpnext-network

volumes:
  mariadb-data:
  erpnext-data:

networks:
  erpnext-network:
    driver: bridge